language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - "7"
# before_install:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
script:
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - dev
